name = input("Hi, i am python what is your name?")
print("Hello, " + name+ ", its nice to meet you!")
age = input("cool name, im 14 how about you?")
print("Your " + age+ "? Thats so cool!")
grade = input("what grade are you in. Im a freshmen.")
print("your a " + grade+ " thats so cool!!!")